### ISSUE TITLE
Can we allow users to select GitHub or IDIR from within Reggie so they don't see the SSO screen?

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/reggie#21]
Rather than a generic "LOGIN" button, it would be nicer if we could allow users to select GitHub or IDIR from within Reggie so they don't see the SSO screen as the SSO screen is umm...not very......aesthetically pleasing. Also one less click/redirect is a better overall UX.

**Comment by ShellyXueHan** [comment]
@sheaphillips I think it's doable. I'll try using the idphint. But the Github extra page will still be there... that's a known bug
