### ISSUE TITLE
Keycloak IDIR account empty email considered duplication

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/reggie#25]
IDIR account with empty email exsits in realm. New IDIR user without email will be considered a duplicating email field. Reggie cannot help in this case as user does not pass through sso login page. Need to discuss with Clecio on solutions.

**Comment by ShellyXueHan** [comment]
IDIR account with empty email exsits in realm. New IDIR user without email will be considered a duplicating email field. Reggie cannot help in this case as user does not pass through sso login page. Need to discuss with Clecio on solutions.

**Comment by lukegonis** [comment]
Blocked until meeting happeneds

**Comment by ShellyXueHan** [comment]
IDIR accounts get an empty string if email is non-existing (GitHub gives null, so working fine). This issues should be solved from https://github.com/bcgov/ocp-sso/issues/13.

Closing.
